### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lokicrown** [esnmechelen/django-test#1]
- [ ] Integrate SumUp w/site (#1 look for API docs)
- [ ] Replace msforms w/own + db + user mgmt non-it ppl (#2 look for aws) [User access as well]
    - [ ] Comms + IT + Events + Side(president/vp/volunteers minder toegang vereist)
- [x] Figma (@Lokicrown )
- [ ] https://esn-amsterdam.nl/events/ should link to WeShre WEB version (+app +call) + link international news to site 
- [ ] Link maps to all partners
- [ ] tumi.esn.world calendar

**Comment by olsonperrensen** [comment]
- [ ] Design db schema w/@Lokicrown
